fix: fixed npm audit issues
contentstack/datasync-asset-store-aws-s3 pull request #3
Opened 2022-09-26 06:32 UTC by vkalta

2022-10-28 12:54 UTC, netrajpatel requested changes
@vkalta Update package versions

2022-10-28 15:53 UTC, aravindbuilt approved these changes

2022-10-30 21:03 UTC, vkalta commented
> @vkalta Update package versions

@netrajpatel Done.

2022-10-31 10:33 UTC, netrajpatel approved these changes

2022-10-31 13:56 UTC, merged